[package]
name = "asaru"
version = "0.1.0"
authors = ["thekuwayama <thekuwayama@gmail.com>"]
description = "Asana Tasks Search CLI"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "2.33"
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
termion = "1.5"